export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const GET_ITEM = 'GET_ITEM';
export const GET_ITEMS = 'GET_ITEMS';
export const ERROR_ITEM = 'ERROR_ITEMS';
export const CLEAR_ITEM = 'CLEAR_ITEM';
export const IMAGE_ITEM = 'IMAGE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';

export const BASKET_TRANSACTIONS = 'GET_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const BASKET_CLEAN = 'BASKET_CLEAN';
export const ERROR_TRANSACTION = 'ERROR_TRANSACTIONS';
export const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION';

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const IS_EDIT = 'IS_EDIT';
export const ERROR_CUSTOMER = 'ERROR_CUSTOMER';
export const CLEAR_CUSTOMER = 'CLEAR_CUSTOMER';

export const GET_MATERIAL = 'GET_MATERIAL';
export const GET_MATERIALS = 'GET_MATERIALS';
export const ERROR_MATERIAL = 'ERROR_MATERIALS';
export const CLEAR_MATERIAL = 'CLEAR_MATERIAL';
export const EDIT_MATERIAL = 'EDIT_MATERIAL';
